# Generated by Django 6.1 on 2026-08-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='creado_en',
            new_name='created_at',
        ),
    ]
